behaviors:
    SnakeAi:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 0.0003
            beta: 0.001
            epsilon: 0.2
            lambd: 0.99
            num_epoch: 3
            shared_critic: False
            learning_rate_schedule: linear
            beta_schedule: linear
            epsilon_schedule: linear
        network_settings:
            normalize: False
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
#            memory: None
            goal_conditioning_type: hyper
            deterministic: False
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        init_path: None
        keep_checkpoints: 5
        even_checkpoints: False
        max_steps: 5000000
        time_horizon: 1000
        summary_freq: 12000
        threaded: False
#        self_play: None
#        behavioral_cloning: None
